#!/bin/sh
#
# This file was produced by running the Configure script. It holds all the
# definitions figured out by Configure. Should you modify one of these values,
# do not forget to propagate your changes by running "Configure -der". You may
# instead choose to run each of the .SH files by yourself, or "Configure -S".
#

# Package name      : dist
# Source directory  : .
# Configuration time: Fri Jan  4 18:37:37 CET 2008
# Configured by     : merijn
# Target system     : linux nb09 2.6.22.13-0.3-default #1 smp 20071119 15:02:58 utc i686 i686 i386 gnulinux 

: Configure command line arguments.
config_arg0='Configure'
config_args='-Dprefix=/pro/3gl/CPAN -des'
config_argc=2
config_arg1='-Dprefix=/pro/3gl/CPAN'
config_arg2='-des'

Author=''
Date=''
Header='$Header'
Id='$Id'
Locker=''
Log='$Log'
RCSfile=''
Revision=''
Source=''
State=''
_a='.a'
_exe=''
_o='.o'
afs='false'
afsroot='/afs'
ar=''
archobjs=''
awk='/usr/bin/awk'
baserev='3.0'
bash=''
bison=''
byacc=''
c=''
cat='/bin/cat'
ccflags='-W -Wall -Wformat=2 -I/usr/local/include'
ccname='gcc'
ccversion=''
cf_by='merijn'
cf_email='merijn@nb09.procura.nl'
cf_time='Fri Jan  4 18:37:37 CET 2008'
chgrp='/home/merijn/bin/private/chgrp'
chmod='/home/merijn/bin/private/chmod'
chown='/home/merijn/bin/private/chown'
comm=''
compress=''
contains='grep'
cp='/bin/cp'
cpio=''
cpp='/usr/bin/cpp'
cpp_trad='/usr/bin/cpp -traditional'
cppflags='-W -Wall -Wformat=2 -I/usr/local/include'
cpplast='-'
cppminus='-'
cpprun='cc -E'
cppstdin='cc -E'
csh=''
d_berknames='undef'
d_bsd='undef'
d_dos='undef'
d_eunice='undef'
d_linux='define'
d_os2='undef'
d_passnames='undef'
d_portable='undef'
d_usgnames='undef'
d_xenix='undef'
date='/bin/date'
defeditor='/usr/bin/vi'
echo='/bin/echo'
egrep=''
emacs=''
eunicefix=':'
expr='/usr/bin/expr'
find=''
firstmakefile=''
flex=''
from=':'
gccosandvers=''
gccversion='4.2.1 (SUSE Linux)'
glibpth='/lib /usr/lib /usr/lib/386 /lib/386 /usr/ccs/lib /usr/ucblib /usr/local/lib'
gmake=''
grep='/usr/bin/grep'
groupcat='cat /etc/group'
gzip=''
hint='default'
hostcat='cat /etc/hosts'
incpath=''
inews='inews'
install='/usr/bin/install'
installdir='mkdir -p'
installmansrc='/usr/local/man/man1'
installprivlib='/pro/3gl/CPAN/lib/dist'
installscript='/usr/local/bin'
issymlink='test -h'
ksh=''
ldflags='-L/usr/local/lib'
less='/pro/local/bin/less'
libpth='/usr/local/lib /lib /usr/lib'
line='/usr/bin/line'
lint=''
lkflags=''
ln='/bin/ln'
lns='/bin/ln -s'
locincpth='/usr/local/include /opt/local/include /usr/gnu/include /opt/gnu/include /usr/GNU/include /opt/GNU/include'
loclibpth='/usr/local/lib /opt/local/lib /usr/gnu/lib /opt/gnu/lib /usr/GNU/lib /opt/GNU/lib'
lp=''
lpr=''
ls=''
mail='/usr/bin/mail'
mailer='/usr/sbin/sendmail'
mailx=''
make='/usr/bin/make'
make_set_make=''
manext='1'
mansrc='/usr/local/man/man1'
mansrcexp='/usr/local/man/man1'
mips_type=''
mkdir='/bin/mkdir'
more='/bin/more'
mv='/bin/mv'
mydomain='.procura.nl'
myhostname='nb09'
myuname='linux nb09 2.6.22.13-0.3-default #1 smp 20071119 15:02:58 utc i686 i686 i386 gnulinux '
n='-n'
nametype='other'
nm=''
nroff='/usr/bin/nroff'
optimize='-O'
orgname='PROCURA B.V.'
osname='linux'
osvers='2.6.22.13-0.3-default'
package='dist'
pager='/pro/local/bin/less'
passcat='cat /etc/passwd'
patchlevel='0'
perl='/pro/bin/perl'
perlpath='/usr/bin/perl'
pg='pg'
phostname='hostname'
pkgsrc='/pro/3gl/CPAN/meta-dist/dist-3.5-20'
plibpth=''
pmake=''
pr=''
prefix='/pro/3gl/CPAN'
prefixexp='/pro/3gl/CPAN'
privlib='/pro/3gl/CPAN/lib/dist'
privlibexp='/pro/3gl/CPAN/lib/dist'
rm='/bin/rm'
rmail='rmail'
run=''
scriptdir='/usr/local/bin'
scriptdirexp='/usr/local/bin'
sed='/usr/bin/sed'
sendmail='/usr/sbin/sendmail'
sh='/bin/sh'
shar=''
sharpbang='#!'
shsharp='true'
sleep=''
smail='smail'
sort='/usr/bin/sort'
spackage='Dist'
spitshell='cat'
src='.'
startperl='#!/usr/bin/perl'
startsh='#!/bin/sh'
submit=''
sysman='/usr/share/man/man1'
tail=''
tar=''
targetarch=''
tbl=''
tee=''
test='test'
to=':'
touch='/usr/bin/touch'
tr='/usr/bin/tr'
trnl='\n'
troff=''
uname='/bin/uname'
uniq='/usr/bin/uniq'
usecrosscompile='undef'
usrinc='/usr/include'
uuname=''
vi='/usr/bin/vi'
xlibpth='/usr/lib/386 /lib/386'
zcat='/usr/bin/zcat'
zip=''
VERSION=3.5
PATCHLEVEL=0
CONFIG=true
